name: Cypress Tests
on:
  push:
    branches:
      - 'Sample134567-patch-1'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
      
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
          
      - name: Write environment variable
        run: 	|
          touch .env
          echo HOST=$${{ secrets.HOST }} >> .env
          echo DEMOHOST=$${{ secrets.DEMOHOST }} >> .env
          echo WEBDRIVERUNI=$${{ secrets.WEBDRIVERUNI }} >> .env
          echo API_URL=$${{ secrets.API_URL }} >> .env
          echo EMAIL=$${{ secrets.EMAIL }} >> .env
          echo PASSWORD=$${{ secrets.PASSWORD }} >> .env
          echo AUTOMATIONSTORE_EMAIL=$${{ secrets.AUTOMATIONSTORE_EMAIL }} >> .env
          echo AUTOMATIONSTORE_PASSWORD=$${{ secrets.AUTOMATIONSTORE_PASSWORD }} >> .env
          echo THRESHOLD=$${{ secrets.THRESHOLD }} >> .env
          echo PROJECTID=$${{ secrets.PROJECTID }} >> .env
          make runChrome
       