name: Cypress Tests
on:
  push:
    branches:
      - 'Sample134567-patch-1'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: make build
        uses: make runChrome